In [1]:
import pandas as pd
import os

In [2]:
os.chdir('..')
print(f'current working directory is {os.getcwd()}')

current working directory is /Users/graciepiantek/Documents/NSS_Projects/open-secrets-three-musketeers

In [3]:
Pol_Cont_df = pd.read_csv('../open-secrets-three-musketeers/data/full_df.csv')

In [4]:
Pol_Cont_df.isna().sum()

cid                  0
FirstLastP           0
Rcpts                0
Spent                0
PACs                 0
Indivs               0
Cand                 0
Other                0
EndCash              0
LgIndivs             0
SmIndivs             0
enddate            363
ReleaseDate          0
VotePercent          0
Result               0
CRPICO               0
State                0
IncCID            1264
Incumbent         1264
primarydate          0
DistIDCurr         363
capeye               0
sort                 0
SmLgIndivsNote       0
District             0
State_Abv            0
dtype: int64

In [5]:
Pol_Cont_df.shape

(1264, 26)

In [6]:
Pol_Cont_df['enddate'].unique() == 'nan'

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [7]:
Pol_Cont_df['enddate'].nunique()

47

In [8]:
Pol_Cont_df['enddate'] == 'nan'

0       False
1       False
2       False
3       False
4       False
        ...
1259    False
1260    False
1261    False
1262    False
1263    False
Name: enddate, Length: 1264, dtype: bool

In [26]:
Pol_Cont_df['enddate']! == 'NaN'

SyntaxError: invalid syntax (3087425293.py, line 1)

In [30]:
Pol_Cont_df['enddate']

0       2020-12-31 00:00:00 +0000
1       2020-12-31 00:00:00 +0000
2       2020-12-31 00:00:00 +0000
3       2020-12-31 00:00:00 +0000
4                             NaN
                  ...
1259    2020-12-31 00:00:00 +0000
1260    2020-12-31 00:00:00 +0000
1261                          NaN
1262                          NaN
1263                          NaN
Name: enddate, Length: 1264, dtype: object

In [32]:
Pol_Cont_df

,cid,FirstLastP,Rcpts,Spent,PACs,Indivs,Cand,Other,EndCash,LgIndivs,...,State,IncCID,Incumbent,primarydate,DistIDCurr,capeye,sort,SmLgIndivsNote,District,State_Abv
0,N00044245,Jerry Carl (R),1971321.50,1859348.91,387000.00,1044195.95,434655.50,105470.05,111972.59,999616.34,...,Alabama,NaN,NaN,2020-03-03 00:00:00 +0000,,0,2,N,1,AL
1,N00044750,James Averhart (D),80094.95,78973.24,0.00,50849.95,29245.00,0.00,1121.71,37954.77,...,Alabama,NaN,NaN,2020-03-03 00:00:00 +0000,,0,2,N,1,AL
2,N00041295,Barry Moore (R),650806.75,669367.70,230281.65,408536.20,11500.00,488.90,-13633.28,346328.65,...,Alabama,NaN,NaN,2020-03-03 00:00:00 +0000,,0,2,N,2,AL
3,N00045944,Phyllis Harvey-Hall (D),56049.68,55988.07,2032.00,42411.95,10575.41,1030.32,0.00,27105.15,...,Alabama,NaN,NaN,2020-03-03 00:00:00 +0000,,0,2,N,2,AL
4,N00045631,John Page (L),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,Alabama,NaN,NaN,2020-03-03 00:00:00 +0000,NaN,0,2,N,2,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1259,N00035504,Liz Cheney (R),3003883.34,3060166.78,1292490.00,1169995.46,0.00,541397.88,153567.15,980348.72,...,Wyoming,NaN,NaN,2020-08-18 00:00:00 +0000,WY01,0,1,N,1,WY
1260,N00047272,Lynnette Grey Bull (D),134597.32,132234.75,2800.00,130197.32,0.00,1600.00,2362.57,65975.00,...,Wyoming,NaN,NaN,2020-08-18 00:00:00 +0000,,0,2,N,1,WY
1261,N00047207,Zoilo Adalia (3),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,Wyoming,NaN,NaN,2020-08-18 00:00:00 +0000,NaN,0,2,N,1,WY
1262,N00035139,Richard Brubaker (L),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,Wyoming,NaN,NaN,2020-08-18 00:00:00 +0000,NaN,0,2,N,1,WY
1263,N00047495,Jeff Haggit (3),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,Wyoming,NaN,NaN,2020-08-18 00:00:00 +0000,NaN,0,2,N,1,WY